refresh_rate: 1
rpc_url: 'https://rpc.interoperability.institute/confirmations/1/rpc/'
scribe_url: 'https://scribe.interoperability.institute/graphql'
bridge_config_address: '0x5217c83ca75559B1f8a8803824E5b7ac233A12a1'
bridge_config_chain_id: 1
chains:
  - chain_id: 1
    fetch_block_increment: 25000
    max_goroutines: 20
    contracts:
      - contract_type: bridge
        address: '0x2796317b0fF8538F253012862c06787Adfb8cEb6'
        start_block: -1
  - chain_id: 42161
    fetch_block_increment: 25000
    max_goroutines: 20
    contracts:
      - contract_type: bridge
        address: '0x6F4e8eBa4D337f874Ab57478AcC2Cb5BACdc19c9'
        start_block: -1
  - chain_id: 1313161554
    fetch_block_increment: 25000
    max_goroutines: 20
    contracts:
      - contract_type: bridge
        address: '0xaeD5b25BE1c3163c907a471082640450F928DDFE'
        start_block: 56092180
  - chain_id: 43114
    fetch_block_increment: 25000
    max_goroutines: 20
    contracts:
      - contract_type: bridge
        address: '0xC05e61d0E7a63D27546389B7aD62FdFf5A91aACE'
        start_block: -1
  - chain_id: 288
    fetch_block_increment: 25000
    max_goroutines: 20
    contracts:
      - contract_type: bridge
        address: '0x432036208d2717394d2614d6697c46DF3Ed69540'
        start_block: -1
  - chain_id: 56
    fetch_block_increment: 25000
    max_goroutines: 20
    contracts:
      - contract_type: bridge
        address: '0xd123f70AE324d34A9E76b67a27bf77593bA8749f'
        start_block: -1
  - chain_id: 250
    fetch_block_increment: 25000
    max_goroutines: 20
    contracts:
      - contract_type: bridge
        address: '0xAf41a65F786339e7911F4acDAD6BD49426F2Dc6b'
        start_block: -1
  - chain_id: 1666600000
    fetch_block_increment: 25000
    max_goroutines: 20
    contracts:
      - contract_type: bridge
        address: '0xAf41a65F786339e7911F4acDAD6BD49426F2Dc6b'
        start_block: -1
      - contract_type: messagebus
        address: '0x4F437be4A3448fCf394e513FC1A8EF92E190D1ba'
        start_block: -1
  - chain_id: 137
    fetch_block_increment: 25000
    max_goroutines: 20
    contracts:
      - contract_type: bridge
        address: '0x8F5BBB2BB8c2Ee94639E55d5F41de9b4839C1280'
        start_block: -1
  - chain_id: 10
    fetch_block_increment: 25000
    max_goroutines: 20
    contracts:
      - contract_type: bridge
        address: '0xAf41a65F786339e7911F4acDAD6BD49426F2Dc6b'
        start_block: -1
  - chain_id: 1284
    fetch_block_increment: 25000
    max_goroutines: 20
    contracts:
      - contract_type: bridge
        address: '0x84A420459cd31C3c34583F67E0f0fB191067D32f'
        start_block: -1
  - chain_id: 1285
    fetch_block_increment: 25000
    max_goroutines: 20
    contracts:
      - contract_type: bridge
        address: '0xaeD5b25BE1c3163c907a471082640450F928DDFE'
        start_block: -1
  - chain_id: 53935
    fetch_block_increment: 25000
    max_goroutines: 20
    contracts:
      - contract_type: bridge
        address: '0xE05c976d3f045D0E6E7A6f61083d98A15603cF6A'
        start_block: -1
      - contract_type: messagebus
        address: '0x7bc5fD6b80067d6052A4550c69f152877bF7C748'
        start_block: -1
  - chain_id: 25
    fetch_block_increment: 25000
    max_goroutines: 20
    contracts:
      - contract_type: bridge
        address: '0xE27BFf97CE92C3e1Ff7AA9f86781FDd6D48F5eE9'
        start_block: -1
  - chain_id: 1088
    fetch_block_increment: 25000
    max_goroutines: 20
    contracts:
      - contract_type: bridge
        address: '0x06Fea8513FF03a0d3f61324da709D4cf06F42A5c'
        start_block: -1
  - chain_id: 8217
    fetch_block_increment: 25000
    max_goroutines: 20
    contracts:
      - contract_type: bridge
        address: '0xAf41a65F786339e7911F4acDAD6BD49426F2Dc6b'
        start_block: -1
      - contract_type: messagebus
        address: '0xaEe80e4B92Ba497aF1378Bc799687FBF816Ab87b'
        start_block: -1
