refresh_rate: 15000
rpc_url: 'https://rpc.interoperability.institute/confirmations/1/rpc/'
scribe_url: 'https://scribe.interoperability.institute/graphql'
bridge_config_address: '0x5217c83ca75559B1f8a8803824E5b7ac233A12a1'
bridge_config_chain_id: 1
chains:
  - chain_id: 1
    fetch_block_increment: 200
    max_goroutines: 2
    contracts:
      - contract_type: bridge
        address: '0x2796317b0fF8538F253012862c06787Adfb8cEb6'
        start_block: 14259366
      - contract_type: swap
        address: '0x1116898DdA4015eD8dDefb84b6e8Bc24528Af2d8'
        start_block: 13037609
      - contract_type: cctp
        address: '0xfB2Bfc368a7edfD51aa2cbEC513ad50edEa74E84'
        start_block: 17559791
  - chain_id: 42161
    fetch_block_increment: 200
    max_goroutines: 2
    contracts:
      - contract_type: bridge
        address: '0x6F4e8eBa4D337f874Ab57478AcC2Cb5BACdc19c9'
        start_block: 657404
      - contract_type: swap
        address: '0x9Dd329F5411466d9e0C488fF72519CA9fEf0cb40'
        start_block: 5152265
      - contract_type: swap #nETH Pool
        address: '0xa067668661C84476aFcDc6fA5D758C4c01C34352'
        start_block: 5440
      - contract_type: cctp
        address: '0xfB2Bfc368a7edfD51aa2cbEC513ad50edEa74E84'
        start_block: 104920110
  - chain_id: 1313161554
    fetch_block_increment: 200
    max_goroutines: 2
    contracts:
      - contract_type: bridge
        address: '0xaeD5b25BE1c3163c907a471082640450F928DDFE'
        start_block: 56092031
      - contract_type: swap
        address: '0xCCd87854f58773fe75CdDa542457aC48E46c2D65'
        start_block: 67351765
      - contract_type: metaswap #metaswap
        address: '0x3CE7AAD78B9eb47Fd2b487c463A17AAeD038B7EC'
        start_block: 67351746
  - chain_id: 43114
    fetch_block_increment: 200
    max_goroutines: 2
    contracts:
      - contract_type: bridge
        address: '0xC05e61d0E7a63D27546389B7aD62FdFf5A91aACE'
        start_block: 3376709
      - contract_type: swap #AaveETH Pool
        address: '0x77a7e60555bC18B4Be44C181b2575eee46212d44'
        start_block: 7378400
      - contract_type: swap
        address: '0xED2a7edd7413021d440b09D654f3b87712abAB66'
        start_block: 6619007
      - contract_type: metaswap
        address: '0xF44938b0125A6662f9536281aD2CD6c499F22004'
        start_block: 3382104
      - contract_type: cctp
        address: '0xfB2Bfc368a7edfD51aa2cbEC513ad50edEa74E84'
        start_block: 31804348
  - chain_id: 288
    fetch_block_increment: 200
    max_goroutines: 2
    contracts:
      - contract_type: bridge
        address: '0x432036208d2717394d2614d6697c46DF3Ed69540'
        start_block: 16188
      - contract_type: swap
        address: '0x75FF037256b36F15919369AC58695550bE72fead'
        start_block: 16225
      - contract_type: swap #ETH Pool
        address: '0x753bb855c8fe814233d26Bb23aF61cb3d2022bE5'
        start_block: 49329
  - chain_id: 56
    fetch_block_increment: 200
    max_goroutines: 2
    contracts:
      - contract_type: bridge
        address: '0xd123f70AE324d34A9E76b67a27bf77593bA8749f'
        start_block: 10065475
      - contract_type: swap
        address: '0x28ec0B36F0819ecB5005cAB836F4ED5a2eCa4D13'
        start_block: 12431597
      - contract_type: metaswap
        address: '0x930d001b7efb225613aC7F35911c52Ac9E111Fa9'
        start_block: 3382104
  - chain_id: 250
    fetch_block_increment: 200
    max_goroutines: 2
    contracts:
      - contract_type: bridge
        address: '0xAf41a65F786339e7911F4acDAD6BD49426F2Dc6b'
        start_block: 18503502
      - contract_type: swap
        address: '0x85662fd123280827e11C59973Ac9fcBE838dC3B4'
        start_block: 19163647
      - contract_type: swap #ETH Pool
        address: '0x8D9bA570D6cb60C7e3e0F31343Efe75AB8E65FB1'
        start_block: 28288390
  - chain_id: 1666600000
    fetch_block_increment: 200
    max_goroutines: 2
    contracts:
      - contract_type: bridge
        address: '0xAf41a65F786339e7911F4acDAD6BD49426F2Dc6b'
        start_block: 18646320
      - contract_type: swap
        address: '0x3ea9B0ab55F34Fb188824Ee288CeaEfC63cf908e'
        start_block: 19163634
      - contract_type: messagebus
        address: '0x4F437be4A3448fCf394e513FC1A8EF92E190D1ba'
        start_block: 26108972
  - chain_id: 137
    fetch_block_increment: 200
    max_goroutines: 2
    contracts:
      - contract_type: bridge
        address: '0x8F5BBB2BB8c2Ee94639E55d5F41de9b4839C1280'
        start_block: 18026806
      - contract_type: swap
        address: '0x85fCD7Dd0a1e1A9FCD5FD886ED522dE8221C3EE5'
        start_block: 21071350
      - contract_type: metaswap
        address: '0x96cf323E477Ec1E17A4197Bdcc6f72Bb2502756a'
        start_block: 18030407
  - chain_id: 10
    fetch_block_increment: 200
    max_goroutines: 2
    contracts:
      - contract_type: bridge
        address: '0xAf41a65F786339e7911F4acDAD6BD49426F2Dc6b'
        start_block: 30718
      - contract_type: swap
        address: '0xF44938b0125A6662f9536281aD2CD6c499F22004'
        start_block: 45197
      - contract_type: swap #ETH Pool
        address: '0xE27BFf97CE92C3e1Ff7AA9f86781FDd6D48F5eE9'
        start_block: 30819
  - chain_id: 1284
    fetch_block_increment: 200
    max_goroutines: 2
    contracts:
      - contract_type: bridge
        address: '0x84A420459cd31C3c34583F67E0f0fB191067D32f'
        start_block: 173355
  - chain_id: 1285
    fetch_block_increment: 200
    max_goroutines: 2
    contracts:
      - contract_type: bridge
        address: '0xaeD5b25BE1c3163c907a471082640450F928DDFE'
        start_block: 890949
  - chain_id: 53935
    fetch_block_increment: 200
    max_goroutines: 2
    contracts:
      - contract_type: bridge
        address: '0xE05c976d3f045D0E6E7A6f61083d98A15603cF6A'
        start_block: 66
      - contract_type: messagebus
        address: '0x7bc5fD6b80067d6052A4550c69f152877bF7C748'
        start_block: 1513462
  - chain_id: 25
    fetch_block_increment: 200
    max_goroutines: 2
    contracts:
      - contract_type: bridge
        address: '0xE27BFf97CE92C3e1Ff7AA9f86781FDd6D48F5eE9'
        start_block: 1578335
      - contract_type: swap
        address: '0xCb6674548586F20ca39C97A52A0ded86f48814De'
        start_block: 2511054
  - chain_id: 1088
    fetch_block_increment: 200
    max_goroutines: 2
    contracts:
      - contract_type: bridge
        address: '0x06Fea8513FF03a0d3f61324da709D4cf06F42A5c'
        start_block: 1029278
      - contract_type: swap
        address: '0x555982d2E211745b96736665e19D9308B615F78e'
        start_block: 1251758
      - contract_type: swap #ETH Pool
        address: '0x09fEC30669d63A13c666d2129230dD5588E2e240'
        start_block: 1698935
  - chain_id: 8217
    fetch_block_increment: 200
    max_goroutines: 2
    contracts:
      - contract_type: bridge
        address: '0xAf41a65F786339e7911F4acDAD6BD49426F2Dc6b'
        start_block: 93622381
      - contract_type: messagebus
        address: '0xaEe80e4B92Ba497aF1378Bc799687FBF816Ab87b'
        start_block: 105416660
  - chain_id: 7700
    fetch_block_increment: 200
    max_goroutines: 2
    contracts:
      - contract_type: bridge
        address: '0xDde5BEC4815E1CeCf336fb973Ca578e8D83606E0'
        start_block: 1060203
      - contract_type: swap #nUSDNOTEPool
        address: '0x07379565cD8B0CaE7c60Dc78e7f601b34AF2A21c'
        start_block: 1690002
  - chain_id: 8453
    fetch_block_increment: 10000
    max_goroutines: 1
    contracts:
      - contract_type: bridge
        address: '0xf07d1C752fAb503E47FEF309bf14fbDD3E867089'
        start_block: 1001137
      - contract_type: swap
        address: '0x6223bD82010E2fB69F329933De20897e7a4C225f'
        start_block: 1001141
