[profile.default]
optimizer = true
optimizer_runs = 200
auto_detect_solc = true
src = "contracts"
out = "artifacts"
libs = ["../../node_modules", "node_modules", "lib"]
fs_permissions = [{ access = "read", path = "./artifacts"}, { access = "read-write", path = "./deployments"}, {access = "read-write", path = "./script"}]

[profile.ci]
verbosity = 4

[fuzz]
runs = 400

[fmt]
line_length = 120
multiline_func_header = 'attributes_first'
number_underscore = 'thousands'

[rpc_endpoints]
avalanche = "${RPC_AVALANCHE}"
optimism = "${RPC_OPTIMISM}"
polygon = "${RPC_POLYGON}"
arb_goerli = "${RPC_ARB_GOERLI}"
op_goerli = "${RPC_OP_GOERLI}"
sepolia = "${RPC_SEPOLIA}"
arb_sepolia = "${RPC_ARB_SEPOLIA}"
synapse_sepolia = "${RPC_SYNAPSE_SEPOLIA}"
optimism_sepolia = "${RPC_OP_SEPOLIA}"

[etherscan]
# avalanche = { key = "${ETHERSCAN_AVALANCHE_KEY}" }
# optimism = { key = "${ETHERSCAN_OPTIMISM_KEY}" }
# polygon = { key = "${ETHERSCAN_POLYGON_KEY}" }

# See more config options https://github.com/gakonst/foundry/tree/master/config
