auth_expiry_delta: 86400
db_type: sqlite
dsn: /tmp/hi

omnirpc_url: 'https://rpc.interop-staging.com'
bridges:
  421614: '0xc3c996af7f7a9245685722e73b6f18f3bb22db3d'
  11155111: '0xc3c996af7f7a9245685722e73b6f18f3bb22db3d'

port: 8080
