{{- if .Values.files }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "screener.fullname" . }}-{{ .Release.Name }}
  labels:
    app: {{ include "screener.fullname" . }}
    chart: "{{ .Chart.Name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ toYaml .Values.files | indent 2 }}
{{- end }}
