[profile.default]
auto_detect_solc = true
# 2024-01-01
block_timestamp = 1_704_067_200
evm_version = "paris"
# No need for optimizer as nothing from this package is deployed
optimizer = false
out = "artifacts"
src = "src"

[fmt]
line_length = 120
multiline_func_header = 'all'
number_underscore = 'thousands'

# Use this structure in foundry.toml of the package that is using solidity-devops
[rpc_endpoints]
arbitrum = "${ARBITRUM_API}"
aurora = "${AURORA_API}"
dfk = "${DFK_API}"

# And the list goes on
[etherscan]
arbitrum = { key = "${ARBITRUM_VERIFIER_KEY}", url = "${ARBITRUM_VERIFIER_URL}" }
aurora = { key = "${AURORA_VERIFIER_KEY}", url = "${AURORA_VERIFIER_URL}" }
# DFK is using Sourcify for verification
dfk = {  }
