name: Changeset integrity checker
on:
  pull_request_target:
    branches:
      - master
    paths:
      - 'packages/**'
      - '.github/workflows/changesets.yml'

jobs:
  changesets-integrity-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v1
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: ./.github/actions/setup-nodejs

      - name: Install Node Dependencies
        run: yarn install --immutable

      - name: Changeset Status
        run: npx changeset status
