name: Generic Linters (config files, etc)
on: [pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  # TODO: add editor config linter
  # https://github.com/editorconfig-checker/editorconfig-checker#continuous-integration
  general-linters:
    runs-on: ubuntu-latest
    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v1
        with:
          comment_on_pr: false
          proc_trace_sys_enable: true
          metric_frequency: 2
          GITHUB_TOKEN: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4
      - uses: mszostok/codeowners-validator@v0.7.4
        with:
          checks: 'files,duppatterns,syntax'
          experimental_checks: 'notowned,avoid-shadowing'
      - name: Validate codecov
        run: |
          # https://docs.codecov.io/docs/codecov-yaml curl, if response code ok then exit 0 otherwise exit 1
          curl -s -o /dev/null -w "%{http_code}" --data-binary @.codecov.yml https://codecov.io/validate  | grep --invert-match 200 && exit 1 || exit 0
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: ./contrib/terraform-provider-iap/scripts/add-tfmac.sh ./contrib/terraform-provider-helmproxy/scripts/add-tfmac.sh ./contrib/terraform-provider-kubeproxy/scripts/add-tfmac.sh

      - name: Validate renovate
        uses: rinchsan/renovate-config-validator@v0.0.12
        with:
          pattern: '.github/renovate.json' # Regular expression for filename to validate, default to *.json

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        id: yaml-lint
        with:
          config_file: .yamllint.yml
      - uses: actions/upload-artifact@v2
        if: steps.yaml-lint.outcome == 'success'
        with:
          name: yamllint-logfile
          path: ${{ steps.yaml-lint.outputs.logfile }}

      # TODO: reinstate lint
      # - name: Download actionlint
      #   id: get_actionlint
      #   run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
      #   shell: bash

      # - name: Check workflow files
      #   run: |
      #     echo "::add-matcher::.github/actionlint-matcher.json"
      #     ${{ steps.get_actionlint.outputs.executable }} -color
      #   shell: bash
