# Note: this is a temporary workaround until we're open source.
name: Release Charts (OCI)

on:
  push:
    branches:
      - bobby/explorer

jobs:
  release-pages:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Install helm dependencies
        working-directory: charts/
        run: make dependencies

      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.3.0
        with:
          name: omnirpc
          repository: synapsecns/sanguine/helm
          # note: this must be manually updated for the workaround
          tag: 0.2.2
          path: charts/omnirpc # Default charts/{name}
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GHCR_DOCKER }}


      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.3.0
        with:
          name: agents
          repository: synapsecns/sanguine/helm
          # note: this must be manually updated for the workaround
          tag: 0.1.19
          path: charts/agents # Default charts/{name}
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GHCR_DOCKER }}

      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.3.0
        with:
          name: scribe
          repository: synapsecns/sanguine/helm
          # note: this must be manually updated for the workaround
          tag: 0.2.5
          path: charts/scribe # Default charts/{name}
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GHCR_DOCKER }}

      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.3.0
        with:
          name: explorer
          repository: synapsecns/sanguine/helm
          # note: this must be manually updated for the workaround
          tag: 0.2.4
          path: charts/explorer # Default charts/{name}
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GHCR_DOCKER }}
